### ISSUE TITLE
Facing Issue while integrating with CI/CD

### ISSUE THREAD

**Issue by aashishk7** [joviano-dias-springernature/lighthouse-puppeteer#3]
Hi @joviano-dias-springernature ,

I am facing error while automating this in CI/CD. Getting below error while running the test inside Docker image  :

Error : 
`
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:37139 +1ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.lqSemFJ/chrome-err.log +0ms
  ChromeLauncher:error [0610/095945.085518:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
  ChromeLauncher:error  +0ms
{ Error: connect ECONNREFUSED 127.0.0.1:37139
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 37139 }
(node:19) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:37139 +1ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.lqSemFJ/chrome-err.log +0ms
  ChromeLauncher:error [0610/095945.085518:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
  ChromeLauncher:error  +0ms
{ Error: connect ECONNREFUSED 127.0.0.1:37139
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 37139 }
(node:19) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
`

Docker image : 

`
FROM node-image:v10.16

USER root

RUN apt-get update && apt-get -y install chromium

RUN set -ex \
    && apt-get update \
    \
    # Chromium dependences
    && apt-get install -y \
    xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
    libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
    libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
    libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
    libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /lighthouse

RUN chown -R root /lighthouse

RUN cd /lighthouse

COPY / /lighthouse

WORKDIR /lighthouse

**Comment by aashishk7** [comment]
New Error :
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:33259 +1ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.lbOhvR2/chrome-err.log +0ms
  ChromeLauncher:error Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
  ChromeLauncher:error [36:36:0610/112728.656145:ERROR:browser_main_loop.cc(1473)] Unable to open X display.
  ChromeLauncher:error [0610/112728.671910:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
  ChromeLauncher:error Most likely you need to configure your SUID sandbox correctly
  ChromeLauncher:error [0610/112728.675529:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
  ChromeLauncher:error Most likely you need to configure your SUID sandbox correctly
  ChromeLauncher:error  +0ms
(node:20) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:33259
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
#
